### PR TITLE
chore: use standard linter locally

### PR DESCRIPTION
**Pull request by erickzhao**
Hi there,

I saw that the build on this project was failing due to code style issues, but there was no way to check the linting status beyond running on the CI or having `standard` installed globally.

I installed ESLint as a dev dependency (with the StandardJS preset) to make it easier to lint locally. `npm run lint` now detects errors locally. Since that command is now available, I added the local linter to the CI.

I also fixed a bug with TravisCI where the config ran on Node 6, which is no longer supported by core nor StandardJS. I replaced it with the latest LTS version of Node.

### CODE REVIEW

**Comment by yan-foto** [comment]
Thanks for the pull request.

"ESLint or Standard" is one of those ongoing struggles (like "vim vs nano vs emacs") that seems to remain unresolved for all eternity! That being said, I see no advantages in using `eslint` over `standard`. If the only problem is "having to install standard globally", you could solve it the same way that you did with `eslint`, namely by putting `standard` in the `devDependencies` and executing it as a node scricpt in `package.json`, i.e.:

```json
"scripts": {
  "lint": "standard main.js"
}
```

and run `node run lint`.

I like the other changes that you made, so I'll keep this PR open, but I'd replace `eslint` with `standard` both in `devDependencies` and `scripts`. What do you reckon?

**Comment by erickzhao** [comment]
@yan-foto Yeah, using ESLint with the StandardJS preset instead of the `standard` package directly doesn't have direct benefits on the code, since it ends up being the same linting rules. I could definitely change this PR to use `standard` directly instead.

**Comment by yan-foto** [comment]
I'd really appreciate it if you would 🙏
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Pmcrypto Golang 0.0.1 (ddacebe0)
Comment: https://protonmail.com

xsBNBFhJMZ8BCAC6QDM4e8qOXZKVC8Zy5mAsv2yh4RJJIPOz0nR+Q6PizHpKMeV0
PM/MXMU/noXlIgyjwd094ZZuUwRyX/g4tmjBBBvX/G4itqWU1K+ec//VB2hO6QlT
mpetItFli66NKquyI7Sng+DGtEEXw9WmUfX02rFO4TBpKDzlBto0ZrJkTi3SSFqo
/MJKiDI40CY1LAo21Q5vSrY7tEivJmMXokW013svWJAtAWMvgarZ0COKHQt9Bjwn
0fAV8njeM7JTPiF6DZOc/9x+4md3ufGb0EDR8GrO8V9sWQzXdZLph7G1zY0J0fKV
gUk2Pi9vWZQmeqgFj5U+EY+AwD10glfUO1SPABEBAAHNGTx5YW4uZm90b0Bwcm90
b25tYWlsLmNvbT7CwHIEEAEIACYFAlhJMaAGCwkIBwMCCRAcvVkyM10o6QQVCAIK
AxYCAQIbAwIeAQAAZKkH/3fsMyb+Xx5JafhPuW4VLXwadtam70t1keG0HuMOp2jl
oDGHasXs0dgD/RFvLV5WjWw1vlOqYtKHcZECNB2wjAm7EmQ3f9w2fv1QhQqlxXbL
NtMrLFEMJhOmf7KdgSx6fSSE2LpnuOGa5cBXb2nb0lGYLuV+oZJTUzWtiKvrcWbe
tOKr6zZeAdCkJ/F1UJkCZ3g0qdIJe5ek8Py7xn+3b4HYJBjjjqhw8YEKpUNK4SGY
qszp+KeAGs4vIGH8HlMeybqkTW3p0XscI6tCNE3GoeYZ2s8BHmfQbuYNS18Ff1/e
4C9lXcjyLm400hf1khBsaYNXnEnyIltlWMTQKkCc2lvOwE0EWEkxnwEIAMd1e+4f
Z6t+VJrSBMftnjlU9X/LubYsd3Q8w/yCO4Z0pc6Z0ZGKLe8feOJlQmP0Ty1mgyDJ
hU7Om3lDxJHj9MeOU6S0g0uhed5TCNiUlaH3/ZZhcya3+O7+LmMIWIelLhGVlZrU
/v6I48fpTi4FVwbOd6IuGGClpgHSV+11caK2/7f1K8YAGW4PGb5kpzzTS8cpedkA
kdLdnWZCz/SHmEnhmjIsXfB5aRm+l/ahhMY0WKIK5IVcdWM/hAczm4MY69xvl36I
3IZwK1albZB43vIrfRQOsYRGbKRaWVXuLLruY7hHpLyJ+3nZgWQMdiM8GMqKVbML
IhjUELC/oTpRXUMAEQEAAcLAXwQYAQgAEwUCWEkxoAkQHL1ZMjNdKOkCGwwAAHCz
B/9zj4RtAJTrslkmRssb6PaLZGx4kVWtRaWP/X60phduXROlcudUymypaznO1keh
mP6khM+9QulubFC54fj3A0dzWsH6fica5H6yhI0Mph3y5mQl6G/wSCBChzzC5o26
SisaDDsFqHqe3J+e5f6rdEGx5ZIa86gMCRC80KoY4zHQm6P+WvUnIOOJmVpttvJ2
of1PILUow+o5Ld0Tiw8yOSiIcj8rHs1pBhYGiGzqjxxmHef/3FQJ77TW1U3+ob43
vBPHq+NNmgzV2KBhQgnCwkvCSyHhvHiQFWWGE3F5O++jXUJYm/350R40yY7CfgGW
Z00M+qS+KszHuIzrPIrN9+wr
=HLW+
-----END PGP PUBLIC KEY BLOCK-----

**Comment by erickzhao** [comment]
@yan-foto done! :)

**Comment by yan-foto** [comment]
Great! Thanks again. I'll merge this into develop first, increase version number and merge with master.

**Pull request merged**
